Initial implementation
dwp/acm-pca-cert-generator pull request #4
Opened 2019-05-24 12:32 UTC by mattburgess

I've renamed the branch at the request of @mark-r-m which had the effect of automatically closing the previous PR. If folks are happy enough after a cursory glance at this I'll promote it from draft PR status to get a proper in depth review done.

2019-05-24 15:53 UTC, dan-hill2802 submitted a review, later dismissed

2019-05-28 10:59 UTC, dan-hill2802 requested changes

2019-05-28 10:59 UTC, dan-hill2802 commented on .circleci/config.yml
> +          sed -i -e "s/version=\"0.0.0\"/version=\"$LATEST_VERSION\" setup.py
need a `"` after the last `\"`

2019-05-28 15:19 UTC, nicholasjgreen approved these changes

2019-05-28 15:35 UTC, dan-hill2802 approved these changes

2019-05-28 15:38 UTC, merged